config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { registrations: "registrations" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :states
  resources :cities
  resources :zipcodes
  resources :galleries
  resources :followings
  resources :pictures
  resources :listings, :except => [:create]
  post '/listings/create', to: 'listings#create'
  post '/listings', to: 'listings#search'
  get '/search_filter', to: 'listings#search_filter'
  post '/simpleSearch', to: 'listings#simpleSearch'
  get '/users/listed', to: 'users#listed', as: 'users_listed'
  root to: "listings#index"
  get '/buy', to: "listings#buy"
  get '/rent', to: "listings#rent"
  get "/home", to: "listings#home"
  post '/contact', to: "users#contact"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstateApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="row navbar-row">
      <ul class="nav navbar-nav">
          <li> <a id="appIcon" href="/home/"> RealEstateApp </a> </li>

          <li> <a href="/buy"> Buy </a> </li> 
          <li> <a href="/rent"> Rent </a> </li> 
          <li> <a href="/states"> States </a> </li>
          <% if user_signed_in? %>
            <li> <%= link_to('Followed', followings_path) %> </li>
          <% end %>  
          <li><a href="/listings/new">Create a Listing</a></li>
      </ul>
      <ul class="nav navbar-nav userInfo">
          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>
            </li>
            <li>
              <%= link_to('Register', new_user_registration_path) %>  
            </li>
          <% end %>      
      </ul>
    </div>
    <div class="row">
      <div id="sRow" class="col-md-12">
        <nav class="navbar searchbar row"> 
          <div class="col-md-2">
            <div class="searchbar_input">
            <%= form_tag(action: "search", controller: "/listings") do |f| %>
              <%= text_field_tag "search_params[address]", '', size: 35, placeholder: "Search Listings..."  %>
            </div>
          </div>
          <div class="col-md-2">

          </div>
          <div class="col-md-1">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle search-drop-down" type="button" data-toggle="dropdown">Price
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= label_tag :min %>:
                <%= text_field_tag "search_params[min_price]", '', size: 8 %>
                <%= label_tag :max %>:
                <%= text_field_tag "search_params[max_price]", '', size: 8 %></li>
              </ul>
            </div>
          </div>
          <div class="col-md-1">

          </div>
          <div class="col-md-2">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle search-drop-down" type="button" data-toggle="dropdown">Area Square Feet
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= label_tag :min %>:
                <%= text_field_tag "search_params[min_area_square_feet]", '', size: 8 %>
                <%= label_tag :max %>:
                <%= text_field_tag "search_params[max_area_square_feet]", '', size: 8 %></li>
              </ul>
            </div>
          </div>
          <div class="col-md-1">

          </div>
          <div class="col-md-1">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle search-drop-down" type="button" data-toggle="dropdown"> Rooms 
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= label_tag :min_bedroom %>:
                <%= text_field_tag "search_params[min_bedroom_count", '', size: 8 %>
                <%= label_tag :min_bathroom %>:
                <%= text_field_tag "search_params[min_bathroom_count", '', size: 8 %></li>
              </ul>
            </div>

          </div>
          <div class="col-md-1">

          </div>
          <div class="col-md-1">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle search-drop-down" type="button" data-toggle="dropdown"> Buy/Rent 
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= label_tag :rent %>:
                  <%= hidden_field_tag "search_params[rent]", false %>
                  <% if request.env['PATH_INFO'] == "/rent"%>
                    <%= check_box_tag "search_params[rent]", true, true %>
                  <% else %>
                    <%= check_box_tag "search_params[rent]", true, false %>
                  <% end %>
                  <%= label_tag :buy %>
                  <%= hidden_field_tag "search_params[buy]", false %>
                  <% if request.env['PATH_INFO'] == "/buy"%>
                    <%= check_box_tag "search_params[buy]", true, true %>
                  <% else %>
                    <%= check_box_tag "search_params[buy]", true, false %>
                  <% end %>        
                  </li>
              </ul>
            </div>

          </div>
          
            <%= submit_tag "", :style => "display: none;"%>
          <% end %>
        </div>
      </div>
      <% if (request.env['PATH_INFO'] == "/home") %>
        <div class="row">
          <%= image_tag("bannerImage", class: "col-md-12", id: "bannerImage") %>
        </div>
      <% end %>
    </div>
    <div class="page_content">
      <%= yield %>
    </div>
    <footer class="row">
      <nav class="nav navbar-custom">
        <ul class="nav navbar-nav">
            <li> <a href="/about"> About </a> </li> 
            <% if user_signed_in? %>
              <li> <%= link_to('Followed', followings_path) %> </li>
            <% end %>  
            <li><a href="/listings/new">Create a Listing</a></li>
        </ul>
      </nav>
    </footer>
  </body>
</html>